### ISSUE TITLE
AttributeError: 'IGService' object has no attribute 'subscribe'

### ISSUE THREAD

**Issue by stuartnmillington** [ig-python/trading-ig#337]
I have installed trading_ig (0.0.22) via pip, and I am running on Ubuntu 24.04. I have downloaded sample/sample_ticker.py from the git website. When I run it I get the following error: AttributeError: 'IGService' object has no attribute 'subscribe'.

I have tried un installing trading_ig with 'pip uninstall trading_ig', checking that the code does not run at all, downloading trading_ig with 'pip install git+https://github.com/ig-python/ig-markets-api-python-library', reinstalling trading_ig and then running the coide again. I still get the same results' The full stacktrace is as follows:

INFO:trading_ig.rest:Creating new v3 session for user 'XXXXXXXXXXXXX' at 'https://demo-api.ig.com/gateway/deal'
INFO:trading_ig.rest:POST '/session', resp 200
INFO:trading_ig.streamer.manager:Consumer: Running
Traceback (most recent call last):
  File "/data/stuart/Projects/Python/BackTesting/TradingPkg/Test_IG_1.py", line 35, in <module>
    main()
  File "/data/stuart/Projects/Python/BackTesting/TradingPkg/Test_IG_1.py", line 23, in main
    sm.start_tick_subscription(epic)
  File "/data/stuart/Projects/Python/Env/lib/python3.12/site-packages/trading_ig/streamer/manager.py", line 39, in start_tick_subscription
    self.service.subscribe(tick_sub)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'IGService' object has no attribute 'subscribe'

I have not been able to find anything else on google to help. Am I missing something here?

Regards Stuart

**Comment by stuartnmillington** [comment]
I have re-downloaded the code for sample_ticker.py and it now appears to be running. Don't know where I wnt wrong, but I will now close this issue.

**Comment by stuartnmillington** [comment]
Not sure how to actually close the issue
